export const recommendedFonts = [
  // sans-serif
  'Archivo',
  'Archivo Narrow',
  'Asap',
  'Asap Condensed',
  'Atkinson Hyperlegible',
  'Atkinson Hyperlegible Mono',
  'Atkinson Hyperlegible Next',
  'Averia Sans Libre',
  'Bai Jamjuree',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Be Vietnam',
  'Chivo',
  'DM Sans',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fira Sans Extra Condensed',
  'Gudea',
  'IBM Plex Sans',
  'IBM Plex Sans Condensed',
  'Inter',
  'Inter Tight',
  'Karla',
  'Lato',
  'Lekton',
  'Libre Franklin',
  'M PLUS 1p',
  'M PLUS Rounded 1c',
  'Mada',
  'News Cycle',
  'Nunito',
  'Nunito Sans',
  'Open Sans',
  'Open Sans Condensed',
  'Oswald',
  'Pragati Narrow',
  'Public Sans',
  'Quattrocento Sans',
  'Quicksand',
  'Roboto',
  'Roboto Condensed',
  'Sarabun',
  'Schibsted Grotesk',
  'Source Sans 3',
  'Work Sans',
  'Yantramanav',
  // serif
  'Abhaya Libre',
  'Adamina',
  'Aleo',
  'Alice',
  'Alike',
  'Alike Angular',
  'Amethysta',
  'Amiri',
  'Andada',
  'Arbutus Slab',
  'Asar',
  'Brawler',
  'Buenard',
  'Cambo',
  'Copse',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Cormorant Upright',
  'Crimson Pro',
  'Crimson Text',
  'Domine',
  'Donegal One',
  'Esteban',
  'Fjord One',
  'Gelasio',
  'IBM Plex Serif',
  'Literata',
  'Petrona',
  'Playfair Display',
  'Solway',
  'Source Serif Pro',
  'Spectral',
  'Trocchi',
  'Vesper Libre',
  'Vollkorn',
  'Zilla Slab',
  // handwriting
  'Meow Script',
  'Ms Madi',
  'Playwrite AT',
  'Playwrite GB J',
  'Playwrite GB S',
  'Sacramento',
  // monospace
  'Anonymous Pro',
  'DM Mono',
  'Fira Code',
  'Fire Mono',
  'Fragment Mono',
  'IBM Plex Mono',
  'Inconsolata',
  'Roboto Mono',
  // display
  'Agbalumo',
  'Bokor',
  'Calistoga',
  'Caprasimo',
  'Miniver',
  'Orelega One',
  'Zen Tokyo Zoo',
]